export const ERROR_RETRY_COUNT = 5;
export const ERROR_RETRY_DELAY = 1000;
export const TOAST_MESSAGE_CLOSE_DELAY = 5000;
export const DEFAULT_REDIS_PORT = 6379;
export const DEFAULT_REDIS_TTL_SEC = 3600;
