import { useError } from "@/context/error-context";
import { GetServerSidePropsContext } from "next";
import { getServerSession } from "next-auth";
import { signIn } from "next-auth/react";
import Head from "next/head";
import { useForm } from "react-hook-form";
import { authOptions } from "../api/auth/[...nextauth]";

interface IEmail {
  email: string;
}

const callbackErrors: { [key: string]: string } = {
  Signin: "Try signing with a different account.",
  OAuthSignin: "Try signing with a different account.",
  OAuthCallback: "Try signing with a different account.",
  OAuthCreateAccount: "Try signing with a different account.",
  EmailCreateAccount: "Try signing with a different account.",
  Callback: "Try signing with a different account.",
  OAuthAccountNotLinked:
    "To confirm your identity, sign in with the same account you used originally.",
  EmailSignin: "Check your email address.",
  CredentialsSignin:
    "Sign in failed. Check the details you provided are correct.",
  default: "Unable to sign in.",
};

const Signin = ({ callbackError }: any) => {
  const { error } = useError();
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<IEmail>();
  const onValid = ({ email }: IEmail) =>
    signIn("email", { email, callbackUrl: "/dashboard" });

  return (
    <>
      <Head>
        <title>Yoshi-POS | Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex items-center justify-center w-full h-screen bg-slate-300">
        <div className="flex items-center justify-center bg-white w-144 h-144">
          <div className="space-y-3">
            <form onSubmit={handleSubmit(onValid)}>
              <div>
                <input
                  {...register("email", {
                    required: "Write your email please",
                    pattern: {
                      value: /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i,
                      message: "Invalid email address",
                    },
                  })}
                  type="email"
                  placeholder="Please input email address"
                  className="border border-blue-500"
                />
                <button className="bg-orange-400">Email Login</button>
                {callbackError && (
                  <p className="text-red-600">Error: {callbackError}</p>
                )}
                {errors.email && (
                  <p className="text-red-600">{errors.email.message}</p>
                )}

                {error === "email-already-in-use" && (
                  <p className="text-red-600">
                    Error: The email is already in use. Please use a different
                    email.
                  </p>
                )}
              </div>
            </form>
            <div className="text-center bg-slate-400">
              <button
                onClick={() => signIn("google", { callbackUrl: "/dashboard" })}
              >
                Google in
              </button>
            </div>
            <div className="text-center bg-slate-400">
              <button
                onClick={() => signIn("line", { callbackUrl: "/dashboard" })}
              >
                Line in
              </button>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Signin;

export async function getServerSideProps(ctx: GetServerSidePropsContext) {
  const session = await getServerSession(ctx.req, ctx.res, authOptions);
  if (session) {
    return {
      redirect: {
        destination: "/dashboard",
      },
    };
  }

  const { error } = ctx.query;
  console.log(error);

  if (error) {
    return {
      props: {
        callbackError:
          callbackErrors[error as string] ?? callbackErrors.default,
      },
    };
  }

  return { props: {} };
}
