import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";
import { useForm } from "react-hook-form";

interface IEmail {
  email: string;
}

export default function Home() {
  const { register, handleSubmit } = useForm<IEmail>();
  const { data: session } = useSession();
  const onValid = ({ email }: IEmail) =>
    signIn("email", { email, callbackUrl: "/" });
  if (session) {
    return (
      <>
        Signed in as {session?.user?.email} <br />
        <button onClick={() => signOut()}>Sign out</button>
      </>
    );
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex items-center justify-center w-full h-screen bg-slate-300">
        <div className="flex items-center justify-center bg-white w-144 h-144">
          <div className="space-y-3">
            Not signed in <br />
            <form onSubmit={handleSubmit(onValid)}>
              <div>
                <input
                  {...register("email", {
                    required: "Write your email please",
                  })}
                  type="email"
                  placeholder="Please input email address"
                  className="border border-blue-500"
                />
                <button className="bg-orange-400">Email Login</button>
              </div>
            </form>
            <div className="text-center bg-slate-400">
              <button onClick={() => signIn("google", { callbackUrl: "/" })}>
                Google in
              </button>
            </div>
            <div className="text-center bg-slate-400">
              <button onClick={() => signIn("line", { callbackUrl: "/" })}>
                Line in
              </button>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
